### PR TITLE
Feat: Implemented Flutter CI

### PR DESCRIPTION
**Pull request by Abhi-0987**
issue: #57 

Implemented the CI Pipeline for the repository, and updated the Kotlin and android tools version.

From now on every PR issue and Merging, the CI will perform certain checks and the branch will be able to get merged only after the CI checks are all passed.

Make sure that you have the latest version of flutter installed before working on the project.
It can be done using flutter upgrade.

Before issuing a PR, make sure that you have performed the following commands, and all the commands are executed without any issues. If any issues are found, clear them before pushing the code.

1. Get flutter dependencies.
    `flutter pub get`
2. Check for any formatting issues in the code.
     `dart run dart_style:format --dry-run --set-exit-if-changed  .`
3. Statically analyze the Dart code for any errors.
   `flutter analyze .`
4. Build apk.
    `flutter build apk`

### CODE REVIEW

**Comment by yagnik2411** [comment]
Current runner version: '2.320.0'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
**Error: Unable to resolve action actions-ecosystem/action-assign, repository not found**      
this error occure

**Comment by Abhi-0987** [comment]
I only implemented CI flow.

That is the error due to the merge of the #55 

The script is not correct in the code of that issue, due to which the error is popping. My script code is working properly. All the PR's that are being issued after merging of #55 are facing this issue.

Please ask @KiranBaliga to look into this issue.

**Comment by KiranBaliga** [comment]
@Abhi-0987 @yagnik2411 I see that greetings.yml is running successfully and looks like there might be an issue with auto-label.yml (I am not sure of it), if you are able to relate to it and if it is the cause, I sincerely apologize for the same. Please remove the file from the repo to evade further errors. I have to attend a medical situation, I regret causing further errorneous contributions. Thank you for your kind understanding!

**Review by yagnik2411 — APPROVED** [review]

**Comment by yagnik2411** [comment]
pubspec .lock has confilcts

**Comment by yagnik2411** [comment]
Current runner version: '2.320.0'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: None
Prepare workflow directory
Prepare all required actions
Getting action download info
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v1`. Learn more: https://github.blog/changelog/[2](https://github.com/yagnik2411/Quiz-Genius/actions/runs/11252505660/job/31308769963?pr=74#step:1:2)024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/    


this is coming from your file

**Pull request merged**
