### PR TITLE
Added issue templates

### PR DESCRIPTION
**Pull request by JomanaMahmoud**
## Pull Request Description

This pull request adds issue templates for improved project management, specifically for:

- **Bug Reports**: A template for users to clearly describe any issues they encounter.
- **Feature Requests**: A template to suggest new functionalities for the project.
- **Documentation Updates**: A template aimed at enhancing existing documentation.
- **Existing Feature Improvements**: A template designed for users to propose enhancements to current features.

This change closes issue #58. 

Additionally, I kindly ask you to add the labels `hacktoberfest-accepted`, `gssoc-ext`, and `level 1` to this pull request, as specified in the issue.

Thank you for your consideration!

### CODE REVIEW

**Comment by yagnik2411** [comment]
you can add a readme file for using this template and add hyperlinks to it.

**Comment by JomanaMahmoud** [comment]
Which template? They already pop up as template options when you click on new issue

**Comment by JomanaMahmoud** [comment]
image
Like this

**Comment by JomanaMahmoud** [comment]
Please before merging add the labels 'gssoc-ext' and 'hacktoberfest-accepted'(not 'hacktoberfest' as this one is not counted towards hacktoberfest ) and 'level1' as specified in the issue, Thank you

**Review by yagnik2411 — APPROVED** [review]

**Pull request merged**
