### PR TITLE
Done the enhancements and also added some new sections

### PR DESCRIPTION
**Pull request by milansamuel609**
I have enhanced the document and also added some new sections

Done the following changes :-

1) Enhanced the project structure
2) Added code of conduct section
3) Added star our repository section
4) Added need help with the basics section
5) Added first pull request steps section
6) Added additional method of contributing through GitHub desktop section
7) Added good coding practices section
8) Added the pull request rules section
9) Added the thank you section

Fixes:[#131 ]
Closes:[#131 ]

image

image

image

image

image

image

image

### CODE REVIEW

**Comment by milansamuel609** [comment]
Done the enhancements. Please kindly check once. If all the changes are fine please merge the PR and also please attach the gssoc extend and level labels.

**Comment by milansamuel609** [comment]
If all the changes are fine please kindly merge the PR.

**Review by KirolosMFahem — CHANGES_REQUESTED** [review]
I'd like you to add that `you should open an issue first and reference it in the PR`

**Comment by milansamuel609** [comment]
> I'd like you to add that `you should open an issue first and reference it in the PR`

@KirolosMFahem I have done the changes please check once.

**Review by KirolosMFahem — APPROVED** [review]

**Pull request merged**
