### PR TITLE
Added username in hamburger menu (Side Drawer)

### PR DESCRIPTION
**Pull request by lavitratyagi1**
There was a issue like it was not displaying name in hamburger menu so i fixed it.

### CODE REVIEW

**Comment by lavitratyagi1** [comment]
This was previously showing 
090014fa-53ce-4741-9f3d-ca4913fa360a

after editing 
72976863-1c5c-4883-b0c2-040f3760eae3

**Review by lavitratyagi2 — APPROVED** [review]

**Comment by yagnik2411** [comment]
did you test this with other username

**Comment by yagnik2411** [comment]
i will test this at weekends .

**Comment by yagnik2411** [comment]
- [ ] participate in gssoc ?
- [ ] participate in hacktoberfest?

**Comment by lavitratyagi1** [comment]
> did you test this with other username
> @lavitratyagi1 goodwork

Yes I have tested it in 2 devices with 3 accounts

**Comment by lavitratyagi1** [comment]
> - [ ] participate in gssoc ?
> - [ ] participate in hacktoberfest?

Yes I have participated in both GSSOC and HACTOBERFEST ' 2024

**Comment by yagnik2411** [comment]
sorry for inconvenience, i will your PR before EOD of 7-10-24

**Review by KirolosMFahem — APPROVED** [review]
as it more friendly with firebsae crashlytics

**Review by yagnik2411 — APPROVED** [review]
@lavitratyagi1  good work

**Comment by KirolosMFahem** [comment]
before merging and closing the PR please add an issue and ask to be assigned to it then add the issue to Development section in the PR

**Comment by lavitratyagi1** [comment]
> before merging and closing the PR please add an issue and ask to be assigned to it then add the issue to Development section in the PR

should i do it now? as this pr is merged?

**Comment by yagnik2411** [comment]
next time @lavitratyagi1

**Pull request merged**
