### PR TITLE
#108 - Password visibility toggle added 

### PR DESCRIPTION
**Pull request by nisarg107**
#108 Sloved - In Login and Signup page password visibility toggle added.

### CODE REVIEW

**Comment by KirolosMFahem** [comment]
please add the issue number to review it @nisarg107

**Comment by nisarg107** [comment]
added issue number kindly review it.

**Comment by KirolosMFahem** [comment]
add the issue number to the PR description or in a comment for this PR

**Review by KirolosMFahem — CHANGES_REQUESTED** [review]
The error in the GitHub Actions job log is related to dependency constraints during the `flutter pub get` step. The log indicates that there are 26 packages with newer versions that are incompatible with the current dependency constraints.

### Steps to Fix the Error:
1. **Update Dependencies**: Run `flutter pub outdated` to see which dependencies need updating. Then update the `pubspec.yaml` file to use compatible versions of these dependencies.
2. **Run `flutter pub get`**: After updating the dependencies, run `flutter pub get` to install the updated packages.
3. **Test the Application**: Ensure that your application still works with the updated dependencies.

Would you like assistance with updating the dependencies?

**Pull request closed without merging**
