### PR TITLE
#16 and #23 issue solved

### PR DESCRIPTION
**Pull request by ezsarthak**
#23 Now it shows a message if an incorrect password is entered and also displays user not found in the respective case

#16 I have created the API of MCQ using the same provider as it was for the True False Quiz. Now user can select between the quiz types and attempt the respective quiz type.

image

### CODE REVIEW

**Comment by yagnik2411** [comment]
sorry for inconvenience, i will your PR before EOD of 7-10-24

**Comment by ezsarthak** [comment]
No problem also please add the required labels.

**Comment by KirolosMFahem** [comment]
Well I see that that error message is well developed, but have you tested the Functionality?

**Review by yagnik2411 — DISMISSED** [review]
@ezsarthak you need to improve in page of the mcq quiz or make a separate screen for it. Because I want  2 by 2 matrix for four options

**Comment by ezsarthak** [comment]
I have now changed the UI of the MCQ page. Made 2 by 2 Matrix for options

**Comment by yagnik2411** [comment]
your file has confilts

**Comment by yagnik2411** [comment]
please pull the latest code and merge it

**Comment by ezsarthak** [comment]
Sorry for it. I have resolved the conflicts.

**Review by ezsarthak — COMMENTED** [review]
#33

**Comment by ezsarthak** [comment]
Please merge this PR and close it

**Comment by ezsarthak** [comment]
@yagnik2411 @KirolosMFahem

**Comment by yagnik2411** [comment]
I will look at it before tomorrow evening

**Comment by yagnik2411** [comment]
hey we some build issues here.
lib/main.dart
Could not format because the source could not be parsed:

line 88, column 1 of lib/models/questions.dart: Expected to find '}'.
   ╷
88 │  
   │ ^
   ╵
line 64, column 1 of lib/models/questions.dart: Classes can't be declared inside other classes.
   ╷
64 │ class Question_MCQ {
   │ ^^^^^
   ╵
line 79, column 1 of lib/models/questions.dart: Classes can't be declared inside other classes.
   ╷
79 │ class Question_T_F {
   │ ^^^^^
   ╵

**Comment by ezsarthak** [comment]
I have solved the errors. Please review it and merge it.

Thank You !!

**Review by KirolosMFahem — CHANGES_REQUESTED** [review]
The recent failure in the GitHub Actions job for the `yagnik2411/Quiz-Genius` repository is due to a formatting error detected by the `dart_style` formatter. The error message indicates that the process completed with exit code 1, which typically means there are code style issues that need to be addressed.

Here are the detailed steps to fix the error:

1. **Run the Formatter Locally**: 
   - Execute the command `dart run dart_style:format .` locally to see the specific code style violations.
   
2. **Update Dependencies**:
   - The logs show several outdated dependencies. Run `flutter pub upgrade` to update the dependencies. You might also need to update the code to be compatible with the latest versions.
   
3. **Fix Code Style Issues**:
   - Once you identify the issues using the formatter, update the code to adhere to the styling guidelines.

4. **Commit Changes**:
   - After fixing the issues, commit the changes and push them to the repository. This should resolve the formatting error and allow the GitHub Actions job to pass.

By following these steps, you can fix the formatting error and ensure that the code adheres to the required style guidelines.

**Comment by yagnik2411** [comment]
Run dart run dart_style:format --dry-run --set-exit-if-changed .
lib/main.dart
Error: Process completed with exit code 1.

**Comment by ezsarthak** [comment]
@yagnik2411 @KirolosMFahem

**Review by KirolosMFahem — APPROVED** [review]
all done

**Comment by ezsarthak** [comment]
image
there is no such error locally. I don't know why it's showing an error for the material library.

**Comment by ezsarthak** [comment]
Thanks @KirolosMFahem .
@yagnik2411 Please Merge this PR

**Comment by yagnik2411** [comment]
I test it and merge it

**Comment by yagnik2411** [comment]
still, we have conflicts in 
lib/pages/quiz_page.dart
pubspec.lock

**Review by ezsarthak — COMMENTED** [review]
Fixed

**Comment by ezsarthak** [comment]
@yagnik2411 @KirolosMFahem

**Review by yagnik2411 — APPROVED** [review]

**Pull request merged**
