### PR TITLE
Fixes #32 Implemented a Confirm Signout dialog box

### LINKED ISSUE #32: Missing Confirmation Dialog on Sign Out
### **Description**

When the user clicks the Sign Out button, they are immediately signed out of the app without any confirmation prompt. This can lead to accidental logouts and may disrupt the user experience, especially if the button is clicked unintentionally.

### **Expected Behaviour**

Before signing out, a confirmation dialog should appear, asking the user to confirm their decision to sign out.
Example dialog: ***"Are you sure you want to sign out?"*** with ***Yes*** and ***No*** options.

### **Actual Behavior**

The user is logged out immediately without any confirmation.

### **Proposed Solution**

Implement a confirmation dialog that appears when the Sign-Out button is clicked, asking the user to confirm their action before proceeding with the sign-out.

### PR DESCRIPTION
**Pull request by T-Soni**
### Overview
This pull request introduces a **Confirm Signout** dialog box that was previously missing from the application. Users now receive a confirmation prompt when they attempt to sign out, preventing accidental logouts.

### What was changed:
- Added a confirmation dialog box that asks the user to confirm or cancel the signout action.
- Updated the signout workflow to trigger the dialog before completing the logout process.
- Aligned the dialog box with the app's existing UI design, fonts, and color palette for consistency.

### Why this solution:
The lack of a confirmation dialog led to accidental signouts, which negatively impacted the user experience. This change provides an extra layer of security and improves overall usability.

### Testing:
- Verified that the dialog appears when the signout button is clicked.
- Tested both confirmation and cancellation flows to ensure correct behavior.

### Screenshot:
Confirm Signout dialog box

Fixes #32

### CODE REVIEW

**Comment by yagnik2411** [comment]
sorry for inconvenience, i will your PR before EOD of 7-10-24

**Comment by T-Soni** [comment]
Could you please add the tags too?

**Review by KirolosMFahem — APPROVED** [review]
more user-friendly and solve miss touch logout

**Review by yagnik2411 — CHANGES_REQUESTED** [review]
@T-Soni You need to follow some ui, you can improve the yes or no button's colour.

**Comment by T-Soni** [comment]
I have made the requested changes to the UI, improving it to align more closely with the existing design and color palette of the app. Please review the updated pull request.

**Comment by T-Soni** [comment]
### **Screenshot:**
WhatsApp Image 2024-10-08 at 14 15 14(1)

**Review by yagnik2411 — APPROVED** [review]

**Pull request merged**
