### PR TITLE
Previous Score screen issue resolved

### LINKED ISSUE #118: [BUG] No previous quiz displayed
**Describe the bug**  
Previous Quiz screen doesn't show any previous quiz even after attempting quiz.
**To Reproduce**  
1. Give some quiz
2. Click on 'previous scores
3. See error

**Expected behavior**  
It should show past record of quiz attempted by the user.

**Screenshots**  
image

**Assignee**:
Feel free to assign this issue to me, as I would like to contribute to its development.

### PR DESCRIPTION
**Pull request by Dhruv80576**
Fix #118 
@yagnik2411 
There was issue with quiz screen it was not updating score on firebase firestore. Now it works perfectly.
Please find screenshot attached to verify it includes both the quizes i.e. true/false and mcq.
image

Can u assign this under Level 2?

### CODE REVIEW

**Comment by Dhruv80576** [comment]
@KirolosMFahem 
Please review pr and merge it

**Comment by yagnik2411** [comment]
@KiranBaliga please reviewit

**Review by KirolosMFahem — APPROVED** [review]
The pull request [#127](https://github.com/yagnik2411/Quiz-Genius/pull/127/files) in the repository `yagnik2411/Quiz-Genius` includes the following changes:

- **File Modified**: `lib/pages/quiz_page.dart`
  - **Commits**:
    - [cd2abcdae45472a24d3be74aacc0a26f52bfb1d2](https://github.com/yagnik2411/Quiz-Genius/commit/cd2abcdae45472a24d3be74aacc0a26f52bfb1d2): "Update quiz_page.dart"

### Summary of Changes:
- Introduced a new method `scoreListAdd` to add new scores.
- Ensured only the last 10 scores are kept in the list.
- Updated scores in Firestore.
- Introduced a method `scoreFetch` to fetch scores from Firestore.
- Modified `scoreUpdate` to clear existing scores and fetch updated scores before adding new scores and maintaining the last 10 scores.

This pull request refactors and enhances the score handling process, including adding, fetching, and updating scores in Firestore, and ensuring only the last 10 scores are retained.

**Comment by KirolosMFahem** [comment]
image

**Comment by KirolosMFahem** [comment]
also I couldn't navigate to the page

**Pull request merged**
