### PR TITLE
Added #53 

### PR DESCRIPTION
**Pull request by ezsarthak**
Now, the user can select the difficulty level while making new quiz

### CODE REVIEW

**Comment by ezsarthak** [comment]
@yagnik2411 @KirolosMFahem

**Comment by yagnik2411** [comment]
lib/pages/quiz_page.dart  have conflicts

**Comment by ezsarthak** [comment]
Please add the required labels. I'm working on it @yagnik2411

**Comment by ezsarthak** [comment]
Can you please guide me how to solve these conflicts

**Comment by ezsarthak** [comment]
> Please add the required labels. I'm working on it @yagnik2411

@KirolosMFahem

**Comment by yagnik2411** [comment]
we have conficts 
lib/pages/quiz_page.dart
pubspec.lock

**Comment by ezsarthak** [comment]
Im working on it. Please add the labels of gssoc and hacktoberfest

**Comment by ezsarthak** [comment]
@yagnik2411 @KirolosMFahem

**Review by yagnik2411 — APPROVED** [review]

**Comment by ezsarthak** [comment]
Sir I have a request, l am a new contributor to GSSOC'24 and have been contributing to this project. However, I have reached the points cap for Level 1, and as I don't have other projects left in my area of expertise, I would like to request a Level 3 tag so I can continue contributing and raise my total points.

**Comment by ezsarthak** [comment]
@KirolosMFahem @yagnik2411

**Comment by yagnik2411** [comment]
> Sir I have a request, l am a new contributor to GSSOC'24 and have been contributing to this project. However, I don't have other projects left in my area of expertise, I would like to request a Level 3 tag so I can continue contributing and raise my total points.

@ezsarthak this is not the way  , we worked.

**Comment by KirolosMFahem** [comment]
> Sir I have a request, l am a new contributor to GSSOC'24 and have been contributing to this project. However, I don't have other projects left in my area of expertise, I would like to request a Level 3 tag so I can continue contributing and raise my total points.

you may check out the issues with level2 or level3 labels since in PR after checking your work I may miss calculate the issue level so I'm upgrading in the PR

or you're working on 2 or more issues in the same PR

**Pull request merged**
