### PR TITLE
Fix entity codes in question

### LINKED ISSUE #19: Bug: Entity codes displayed instead of the required character
I've noticed that the entity codes are being displayed instead of the actual characters in the quiz questions.
Egs: &-quot; in place of quotes(") and &-#039; in place of apostrophe(')

WhatsApp Image 2024-10-02 at 19 47 21_3e78b323

### PR DESCRIPTION
**Pull request by aashika-j18**
This PR ensures that the actual characters like quotes(") and apostrophes(') are displayed in the question instead of their entity code.

Fixes #19.

Screenshot 2024-10-12 000828
Screenshot 2024-10-12 001038

### CODE REVIEW

**Comment by aashika-j18** [comment]
Please review and let me know if further changes are required!
Please assign the required hacktoberfest, gssoc-ext and level labels as well.
Thank You!

**Comment by KirolosMFahem** [comment]
The failure occurred due to the following errors in the `lib/utils/profile_image_service.dart` file:

1. **URI Doesn't Exist**:
   - The import statement for `flutter/material.dart` has an extra space which makes it invalid.
   ```
   import 'package:flutter/material.dart ';
   ```

2. **Undefined Identifiers**:
   - The identifier `Colors` is undefined. This is due to the incorrect import statement mentioned above.

### Recent Changes

The recent commit that affected this file was:
- [d0e39b4](https://github.com/yagnik2411/Quiz-Genius/commit/d0e39b46f816e9e9b593a7fcbb49da1387c6630d): "Add Image Upload Feature".

### Suggested Fixes

1. Correct the import statement for `flutter/material.dart` by removing the extra space:
   ```dart
   import 'package:flutter/material.dart';
   ```

2. Ensure that the `Colors` class is properly referenced by fixing the import statement.

By correcting the import statement, the identifier `Colors` will be recognized, and the errors should be resolved.

**Comment by aashika-j18** [comment]
I have fixed the import error.
Please review and let me know.

**Review by KirolosMFahem — CHANGES_REQUESTED** [review]
### Analysis of Error
The error in the logs indicates that the Android Gradle plugin requires Java 17, but the current environment is using Java 12. Here is the relevant log message:

```
Android Gradle plugin requires Java 17 to run. You are currently using Java 12.
Your current JDK is located in /opt/hostedtoolcache/jdk/12.0.2/x64
```

### Steps to Fix the Issue
1. **Update the Java Version in the CI/CD Pipeline:**
   - Modify the GitHub Actions workflow file to use Java 17 instead of Java 12.

### Example Update to GitHub Actions Workflow
Here is an example of how you can update the workflow file to use Java 17:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build with Gradle
        run: ./gradlew build
```

### Summary
The failure is due to the Android Gradle plugin requiring Java 17. Updating the GitHub Actions workflow to use Java 17 should resolve the issue.

**Review by KirolosMFahem — APPROVED** [review]
all done

**Comment by yagnik2411** [comment]
we have conflicts in quiz_page.dart

**Comment by yagnik2411** [comment]
we have some conflcts in 
line 363, column 7 of lib/pages/quiz_page.dart: Expected to find ')'.
    ╷
363 │       }
    │       ^
    ╵

**Review by KirolosMFahem — CHANGES_REQUESTED** [review]
.

**Review by KirolosMFahem — APPROVED** [review]

**Comment by KirolosMFahem** [comment]
@yagnik2411 it's good to go
test it out and merge it

**Pull request merged**
