### PR TITLE
display counter added

### PR DESCRIPTION
**Pull request by 17arindam**
- i have added a display counter on the appbar of the quiz 
- the quiz will be submitted once the timer goes off
Screenshot 2024-10-11 231439

### CODE REVIEW

**Review by KirolosMFahem — CHANGES_REQUESTED** [review]
### Error Analysis and Fix Plan

#### Logs Analysis:
The job failed with the following error:
```
Process completed with exit code 1.
```
The logs show that there are outdated dependencies:
```
45 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
```

#### Related File Changes:
The main file modified in PR 82 is `lib/pages/quiz_page.dart` with the following changes:
- Added a timer to the quiz page.
- Modified the `initState`, `dispose`, and other methods to handle the timer.
- Updated the `showSubmissionConfirmationDialog` method.

#### Steps to Fix:
1. **Update Dependencies:** Run `flutter pub outdated` and update the dependencies to compatible versions as indicated.
2. **Check Timer Implementation:** Ensure the timer logic is correctly implemented without causing runtime errors.

Would you like to proceed with updating the dependencies and checking the timer implementation in the code?

**Comment by KirolosMFahem** [comment]
send me the issue number

**Comment by 17arindam** [comment]
@KirolosMFahem issue no #39

**Comment by 17arindam** [comment]
@KirolosMFahem i have updated the dependecies of flutter please review my changes

**Comment by KirolosMFahem** [comment]
The error in the logs is:

```
##[error]Process completed with exit code 1.
```

The log indicates that there was an issue with the formatting check step, which uses `dart run dart_style:format --dry-run --set-exit-if-changed .`. 

To fix this error:
1. Run `dart format .` locally to format the Dart code.
2. Commit and push the changes to the repository.

This should resolve the formatting issues causing the CI/CD pipeline to fail.

**Comment by yagnik2411** [comment]
we have confilcts in quiz_page.dart

**Comment by 17arindam** [comment]
@yagnik2411 conflicts resolved

**Comment by yagnik2411** [comment]
your PRs ensuffiecient

**Pull request merged**
